version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: reactapp:v1
    container_name: reactapp-example
    restart: unless-stopped
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app